### ISSUE TITLE
Palautetta osista 1­–5

### ISSUE THREAD

**Issue by ollpu** [hy-tikawe/materiaali#1]
### Osa 1

- `<label>`-tagin käyttö ainakin radio/checkboxien kanssa olisi hyvän tavan mukaista:
  ```
  <label><input type="radio" name="pizza" value="1" /> Frutti di Mare</label>
  <label><input type="radio" name="pizza" value="2" /> Margherita</label>
  ```
- radio/checkboxien eron selityksen viereen voisi laittaa interaktiivisen demon HTML:llä
- Voisi mainita, että puuttuvasta `favicon.ico`sta tulevat virheet eivät ole ongelma ja voi jättää huomiotta ainakin toistaiseksi (opiskelija ihmetteli joskus)

### Osa 2

- "sovelluksen käyttäminen voi näyttää seuraavalta" -> video?
- Debuggaukseen liittyen voisi mainita `flask --debug`, jopa ennemmin kuin lokien kahlaamisen. Se näyttää virheet selaimessa + integroitu debuggeri

### Osa 3

- Secretin salaaminen jää vähän epäselväksi.
  - Opastus sen laittamisesta gitignoreen?
  - Eri avaimet tuotannossa ja prodissa?
  - Miten vertaisarvioijien tulisi toimia?
  
  Mahdollinen ratkaisu olisi todeta, että kehitykseen käytettävä avain on julkinen, mutta tämä pitää muuttaa ennen sovelluksen julkaisemista.

- Jotain yleisiä huomiota salasanaturvallisuudesta? Hashaus(+suolaus) ei tarkoita että voi käyttää samaa salasanaa kuin muualla, miksi käytetään valmista toteutusta, yms
- Kirjautumisessa käytetään `db.query_one`. Mistä se ilmestyi?

### Osa 4

- `get_threads` funktion yhteydessä voisi mainita tulossarakkeiden nimeämisen merkityksen, ja että samat nimet tosiaan toimii siellä templatessa asti

### Osa 5

- Antaisin "ongelmille" nimet otsikoihin, jotta kokonaisuus on helpompi hahmottaa

### Yleistä

- Linkkeihin `url_for` olisi siistimpi ja hyvä tapa opettaa (vähintään mainita)
- Jinjan tekemä escapetus (Markupsafe yms) mainitaan ohimennen, mutta voisi kertoa selkeämmin mitä tapahtuu (sitten kun asia ei hoidukaan automaattisesti jossain toisessa tilanteessa)
- Joissain lomakkeissa käytettiin `input type=hidden`, joissain URL-parametria. Miten valita näiden välillä? (tai miksi molemmat esitellään)

**Comment by pllk** [comment]
Osassa 9 käsitellään label-elementtiä, tosin siellä käsittelyä voisi ehkä laajentaa. Osassa 8 käsitellään escapetusta, tätäkin voisi laajentaa/parantaa nykyisestä.

Videot on hyvä idea ja voisi sopia moneenkin kohtaan materiaalissa.

Tehtävälista:

- [ ] radio/checkboxien eron selityksen viereen interaktiivinen demo HTML:llä
- [ ] mitä puuttuva `favicon.ico` tarkoittaa ja haittaako?
- [ ] debuggaus komennolla `flask --debug`
- [ ] secretin salaaminen ja ohjeistus omaan projektiin
- [ ] tarkemmin salasanaturvallisuudesta
- [ ] poista `db.query_one` joka oli materiaalin aiemmassa versiossa
- [ ] `get_threads` yhteydessä tulossarakkeiden nimien merkitys, toimii templatessa
- [ ] osassa 5 paremmat otsikot
- [ ] `url_for` maininta linkkien tekemiseen (ei ehkä muutos kaikille koska bloatti)
- [ ] milloin/miksi käyttää `input type=hidden` tai URL-parametria
